---
# https://git.zdt.io/misc/gitlab_templates
include:
  - project: "misc/gitlab_templates"
    ref: master
    file: "/molecule/.base-template.yml"
  - project: "misc/gitlab_templates"
    ref: master
    file: "/.clone-before-script-template.yml"

stages:
  - ansible-2.9.docker
  - ansible-2.9.vm

# images link
# https://cloud.docker.com/u/zerodowntime/repository/docker/zerodowntime/gitlab_runner_executor_molecule

# job docker
ansible-2.9.docker:
  extends: .molecule.default
  stage: ansible-2.9.docker
  image: zerodowntime/gitlab_runner_executor_molecule:ansible-2.9-molecule-3.0
  script:
    - molecule test -s docker

# job vm
ansible-2.9.vm:
  extends: .molecule.default
  stage: ansible-2.9.vm
  image: zerodowntime/gitlab_runner_executor_molecule:ansible-2.9-molecule-3.0
  script:
    - molecule test
