---
# https://molecule.readthedocs.io/en/latest/configuration.html
dependency:
  name: galaxy
  options:
    role-file: molecule/shared/requirements.yml

driver:
  name: docker

lint: |
  set -e
  yamllint -c molecule/shared/.yaml_lint.yml .
  ansible-lint -c molecule/shared/.ansible-lint.yml
  flake8

platforms:
  - name: "${ROLE_CI_PREFIX:-d}-centos7"
    image: "centos:centos7"
    privileged: false
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - centos

provisioner:
  name: ansible
  log: true
  playbooks:
    converge: ../shared/converge.yml
  config_options:
    diff:
      always: true
  inventory:
    group_vars:
      ubuntu:
        ansible_python_interpreter: /usr/bin/python3

scenario:
  test_sequence:
    - lint
    - destroy
    # - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy

verifier:
  name: ansible
  enabled: false
